# Generated by Codex on 2026-02-04
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_add_chatsession_and_session_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserQuota",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quota_bytes", models.BigIntegerField(default=104857600)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="auth.user")),
            ],
        ),
    ]

