# Generated by Django 6.0.1 on 2026-02-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquota',
            name='quota_bytes',
            field=models.BigIntegerField(default=10485760),
        ),
    ]
