# Generated by Django 6.0.1 on 2026-02-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_rename_core_userlo_is_acti_1f1838_idx_core_userlo_is_acti_22952d_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemHealthSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                ("cpu_percent", models.FloatField(default=0.0)),
                ("memory_percent", models.FloatField(default=0.0)),
                ("disk_percent", models.FloatField(default=0.0)),
                ("load_1m", models.FloatField(default=0.0)),
                ("active_sessions", models.PositiveIntegerField(default=0)),
                ("online_users_non_staff", models.PositiveIntegerField(default=0)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "ordering": ["-captured_at"],
            },
        ),
        migrations.AddIndex(
            model_name="systemhealthsnapshot",
            index=models.Index(fields=["captured_at"], name="core_systemh_captured_259f23_idx"),
        ),
        migrations.AddIndex(
            model_name="systemhealthsnapshot",
            index=models.Index(fields=["captured_at", "cpu_percent"], name="core_systemh_capture_9ee35f_idx"),
        ),
    ]
