# Generated by Django 6.0.1 on 2026-02-19 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0015_systemhealthsnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="RagRequestMetric",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_id", models.CharField(db_index=True, max_length=64)),
                ("mode", models.CharField(default="dense", max_length=32)),
                ("query_len", models.PositiveIntegerField(default=0)),
                ("dense_hits", models.PositiveIntegerField(default=0)),
                ("bm25_hits", models.PositiveIntegerField(default=0)),
                ("final_docs", models.PositiveIntegerField(default=0)),
                ("retrieval_ms", models.PositiveIntegerField(default=0)),
                ("rerank_ms", models.PositiveIntegerField(default=0)),
                ("llm_model", models.CharField(blank=True, default="", max_length=255)),
                ("llm_time_ms", models.PositiveIntegerField(default=0)),
                ("fallback_used", models.BooleanField(default=False)),
                ("source_count", models.PositiveIntegerField(default=0)),
                ("status_code", models.PositiveIntegerField(default=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rag_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ragrequestmetric",
            index=models.Index(fields=["created_at"], name="core_ragreq_created_56a5b7_idx"),
        ),
        migrations.AddIndex(
            model_name="ragrequestmetric",
            index=models.Index(fields=["status_code", "created_at"], name="core_ragreq_status__95f6fe_idx"),
        ),
        migrations.AddIndex(
            model_name="ragrequestmetric",
            index=models.Index(fields=["fallback_used", "created_at"], name="core_ragreq_fallbac_621997_idx"),
        ),
    ]
