# Generated by Django 6.0.1 on 2026-02-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_ragrequestmetric"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="admin_dashboard_locale",
            field=models.CharField(default="id", max_length=16),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="admin_metrics_retention_days",
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="admin_realtime_max_rows",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="admin_realtime_poll_seconds",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
