# Generated by Django 6.0.1 on 2026-02-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_systemsetting_admin_dashboard_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ragrequestmetric',
            new_name='core_ragreq_created_0e1d24_idx',
            old_name='core_ragreq_created_56a5b7_idx',
        ),
        migrations.RenameIndex(
            model_name='ragrequestmetric',
            new_name='core_ragreq_status__2ef1f8_idx',
            old_name='core_ragreq_status__95f6fe_idx',
        ),
        migrations.RenameIndex(
            model_name='ragrequestmetric',
            new_name='core_ragreq_fallbac_970bb4_idx',
            old_name='core_ragreq_fallbac_621997_idx',
        ),
        migrations.RenameIndex(
            model_name='systemhealthsnapshot',
            new_name='core_system_capture_be2d91_idx',
            old_name='core_systemh_captured_259f23_idx',
        ),
        migrations.RenameIndex(
            model_name='systemhealthsnapshot',
            new_name='core_system_capture_d0e4fb_idx',
            old_name='core_systemh_capture_9ee35f_idx',
        ),
    ]
