# Generated by Django 6.0.1 on 2026-02-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_plannerrun'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='plannerrun',
            new_name='core_planne_user_id_a063a4_idx',
            old_name='core_planne_user_id_81de39_idx',
        ),
        migrations.RenameIndex(
            model_name='plannerrun',
            new_name='core_planne_expires_dcc37c_idx',
            old_name='core_planne_expires_73ca74_idx',
        ),
    ]
