# Generated by Django 6.0.1 on 2026-02-22 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_plannerrun_v32_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ragrequestmetric',
            name='answer_mode',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='ragrequestmetric',
            name='intent_route',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='ragrequestmetric',
            name='pipeline',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='ragrequestmetric',
            name='validation',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='ragrequestmetric',
            index=models.Index(fields=['pipeline', 'created_at'], name='core_ragreq_pipelin_8a01d5_idx'),
        ),
        migrations.AddIndex(
            model_name='ragrequestmetric',
            index=models.Index(fields=['validation', 'created_at'], name='core_ragreq_validat_c852e3_idx'),
        ),
        migrations.AddIndex(
            model_name='ragrequestmetric',
            index=models.Index(fields=['intent_route', 'created_at'], name='core_ragreq_intent__46c60b_idx'),
        ),
        migrations.AddIndex(
            model_name='ragrequestmetric',
            index=models.Index(fields=['answer_mode', 'created_at'], name='core_ragreq_answer__6e5102_idx'),
        ),
    ]
